language: python
python:
  - "3.6"
dist: trusty
sudo: required
addons:
  firefox: "60.0.1"
install:
  - pip install -r requirements.txt
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
before_script:
  - python manage.py runserver &
script:
  - python manage.py test